permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 梁彬
  email: 609498751@qq.com
  link: lbrb.github.io
#  weibo: http://weibo.com/yansu0711
  github: http://github.com/lbrb

# 站点信息
title: 梁彬的博客
description: 梁彬的博客
url: lbrb.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://en.gravatar.com/avatar/daa7fa143a3eb3f4c43ea30ffdc1ccc8
favicon: http://en.gravatar.com/avatar/daa7fa143a3eb3f4c43ea30ffdc1ccc8

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: liangbin

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
